name: i9star-prd
services:
  app:
    build: .
    container_name: i9star_app_prd
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.prd
    depends_on:
      - postgres
    networks:
      - i9star_prd_network

  postgres:
    image: postgres:16
    container_name: i9star_postgres_prd
    restart: unless-stopped
    env_file:
      - .env.prd
    volumes:
      - i9star_prd_postgres_data:/var/lib/postgresql/data
    networks:
      - i9star_prd_network

volumes:
  i9star_prd_postgres_data:

networks:
  i9star_prd_network:
    driver: bridge
