name: i9star-dev

services:
  app:
    build:
      context: .
      args:
        GIT_COMMIT: 9835fe8
    container_name: i9star_app_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - uploads_dev:/usr/src/app/uploads

  postgres:
    image: postgres:16-alpine
    container_name: i9star_postgres_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata_dev:
  uploads_dev:
